#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycv-deployment
spec:
  selector:
    matchLabels:
      app: mycv-server
  replicas: 3
  template:
    metadata:
      labels:
        app: mycv-server
    spec:
      containers:
      - name: mycv-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/fmclovin/mycvmat:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mycv-service
  name: mycv-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mycv-server
  type: LoadBalancer
